In [6]:
import numpy as np
import sys
from mido import MidiFile, MidiTrack, Message, MetaMessage

def decode_midi(filename, maxnotes = 0):
    
    mid_in = MidiFile(filename)
    notes = []
    for track in mid_in.tracks:
        sum_of_ticks = 0
        pool = []
        for msg in track:
            sum_of_ticks += msg.time
            if msg.type=='note_on':
                for p in pool:
                    if p[1]==msg.channel and p[2]==msg.note:
                        if sum_of_ticks-p[0]>0: notes.append([p[0], p[2], sum_of_ticks-p[0]])
                        pool.remove(p)
                        break
                else: pool.append([sum_of_ticks, msg.channel, msg.note])
            if msg.type=='note_off':
                for p in pool:
                    if p[1]==msg.channel and p[2]==msg.note:
                        if sum_of_ticks-p[0]>0: notes.append([p[0], p[2], sum_of_ticks-p[0]])
                        pool.remove(p)
                        break
        for p in pool:
            if sum_of_ticks-p[0]>0: notes.append([p[0], p[2], sum_of_ticks-p[0]])

    notes = np.array(notes)
    ticks = np.unique(notes[:,0])
    
    pack = []
    for idx in range(len(ticks)-1):
        notes_at_ticks = np.unique(notes[notes[:,0]==ticks[idx]], axis=0)
        chord = str([p for p in notes_at_ticks[-maxnotes:,1]])
        pack.append(chord)
    return pack

def encode_midi(filename, data, tempo_set=500000):
    
    mid_out = MidiFile()
    track = MidiTrack()
    mid_out.tracks.append(track)

    track.append(Message('program_change', program=46, time=0))
    track.append(MetaMessage('set_tempo', tempo=tempo_set, time=0))
    for pack in data:
        
        chord = eval(pack)
        delay = 120
        for pit in chord:
            track.append(Message('note_on', note=pit, velocity=64, time=0))
        track.append(Message('note_off', note=chord[0], velocity=64, time=delay))
        for pit in chord[1:]:
            track.append(Message('note_off', note=pit, velocity=64, time=0))

    mid_out.save(filename)



In [1]:
import sys
print(sys.path)

['C:\\Users\\user\\Desktop\\研究所\\程式\\ML', 'C:\\Users\\user\\Anaconda3\\python37.zip', 'C:\\Users\\user\\Anaconda3\\DLLs', 'C:\\Users\\user\\Anaconda3\\lib', 'C:\\Users\\user\\Anaconda3', '', 'C:\\Users\\user\\Anaconda3\\lib\\site-packages', 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\user\\.ipython']


In [2]:
from midi_phraser import *

data = decode_midi('C:/Users/user/Desktop/研究所/程式/ML/midi_files/mozk219a.mid')

for idx, chord in enumerate(data):
    print('#%d: %s' % (idx,chord))

encode_midi('test.mid', data)

#0: [33, 45, 61, 64, 69]
#1: [45, 49, 52]
#2: [57]
#3: [45, 49, 52]
#4: [57]
#5: [45, 49, 52]
#6: [57]
#7: [45, 49, 52]
#8: [57]
#9: [45, 49, 52]
#10: [57]
#11: [45, 49, 52, 61]
#12: [57]
#13: [45, 49, 52]
#14: [57]
#15: [45, 49, 52, 64]
#16: [57]
#17: [45, 49, 52]
#18: [57]
#19: [45, 49, 52, 69]
#20: [57]
#21: [45, 49, 52]
#22: [57]
#23: [45, 49, 52, 73]
#24: [57]
#25: [45, 49, 52]
#26: [57]
#27: [45, 49, 52, 64]
#28: [57]
#29: [45, 49, 52]
#30: [57]
#31: [57, 61, 69]
#32: [64]
#33: [57, 61]
#34: [64]
#35: [57, 61, 73]
#36: [64]
#37: [57, 61]
#38: [64]
#39: [57, 61, 76]
#40: [64]
#41: [57, 61]
#42: [64]
#43: [57, 61, 69]
#44: [64]
#45: [57, 61]
#46: [64]
#47: [57, 61, 73]
#48: [64]
#49: [57, 61]
#50: [64]
#51: [57, 61, 76]
#52: [64]
#53: [57, 61]
#54: [64]
#55: [57, 61, 81]
#56: [64]
#57: [57, 61]
#58: [64]
#59: [57, 61, 85]
#60: [64]
#61: [57, 61]
#62: [64]
#63: [52, 64, 76, 80, 86]
#64: [83]
#65: [85]
#66: [40, 52, 86]
#67: [52, 56]
#68: [59]
#69: [52, 56]
#70: [59]
#71: [52, 56, 62

#2011: [49, 61]
#2012: [61, 73]
#2013: [57, 69]
#2014: [52, 64]
#2015: [57, 69]
#2016: [49, 61]
#2017: [52, 64]
#2018: [45, 57]
#2019: [49, 61]
#2020: [52, 64]
#2021: [57, 69, 69]
#2022: [73]
#2023: [76]
#2024: [81]
#2025: [73, 76, 81]
#2026: [71, 74, 80]
#2027: [69, 73, 78]
#2028: [52, 68, 71, 75]
#2029: [76]
#2030: [56]
#2031: [59]
#2032: [64, 76]
#2033: [80]
#2034: [83]
#2035: [86]
#2036: [78, 81, 86]
#2037: [76, 80, 85]
#2038: [74, 78, 83]
#2039: [45, 73, 76, 80]
#2040: [81]
#2041: [49]
#2042: [52]
#2043: [57, 81]
#2044: [85]
#2045: [88]
#2046: [93]
#2047: [64, 69, 73, 91]
#2048: [62, 74, 90]
#2049: [61, 69, 89]
#2050: [50, 62, 69, 89]
#2051: [50, 90]
#2052: [50, 90]
#2053: [50, 74]
#2054: [78]
#2055: [50, 57, 81]
#2056: [50]
#2057: [50, 88]
#2058: [50, 61]
#2059: [64]
#2060: [54, 88]
#2061: [54, 86]
#2062: [54, 86]
#2063: [54, 73]
#2064: [76]
#2065: [54, 81]
#2066: [54]
#2067: [52, 85]
#2068: [52, 61]
#2069: [64]
#2070: [50, 59, 66, 69, 83]
#2071: [85]
#2072: [83]
#2073: [82]
#207

In [34]:
from midi_phraser import *

data = decode_midi('C:/Users/user/Desktop/研究所/程式/ML/midi_files/mozk219a.mid')

all_chords = sorted(set(data))
n_chords = len(all_chords)
chords_to_idx = dict((v, i) for i,v in enumerate(all_chords))
idx_to_chords = dict((i, v) for i,v in enumerate(all_chords))

print('Total # of chords:',n_chords)
for key in chords_to_idx:
    print(key,'==>',chords_to_idx[key])

print('Encoded data:')
for p in data:
    print(chords_to_idx[p],'',end='')
print(',',len(data),'notes in total.')

Total # of chords: 792
[100] ==> 0
[33, 45, 61, 64, 69, 81] ==> 1
[33, 45, 61, 64, 69] ==> 2
[36, 48, 60, 80] ==> 3
[37, 49, 61, 78] ==> 4
[38, 50, 59, 66, 69, 71] ==> 5
[39, 51, 63, 73] ==> 6
[39, 51, 66] ==> 7
[39, 51, 71, 78, 81, 83] ==> 8
[39, 51, 72] ==> 9
[40, 47, 52, 56, 64] ==> 10
[40, 52, 59, 64, 68, 71] ==> 11
[40, 52, 62, 86] ==> 12
[40, 52, 64, 68, 68, 71, 71, 76] ==> 13
[40, 52, 64, 73] ==> 14
[40, 52, 64] ==> 15
[40, 52, 68, 74, 76, 83] ==> 16
[40, 52, 68] ==> 17
[40, 52, 73, 76, 81, 85] ==> 18
[40, 52, 73, 81, 85] ==> 19
[40, 52, 73] ==> 20
[40, 52, 83] ==> 21
[40, 52, 86] ==> 22
[40, 52, 88] ==> 23
[41, 53, 74] ==> 24
[42, 54, 63] ==> 25
[42, 54, 74, 81, 86] ==> 26
[42, 60, 63, 76] ==> 27
[43, 76] ==> 28
[45, 49, 52, 57, 61, 64, 64, 69, 73, 81] ==> 29
[45, 49, 52, 57, 61, 64, 69] ==> 30
[45, 49, 52, 57, 64, 69, 73] ==> 31
[45, 49, 52, 57, 74] ==> 32
[45, 49, 52, 57, 78] ==> 33
[45, 49, 52, 57] ==> 34
[45, 49, 52, 61, 81] ==> 35
[45, 49, 52, 61] ==> 36
[45, 49, 52, 64, 8

[68, 76, 83] ==> 675
[68, 76] ==> 676
[68, 80] ==> 677
[68, 86] ==> 678
[68] ==> 679
[69, 71, 75, 78] ==> 680
[69, 72, 87] ==> 681
[69, 72] ==> 682
[69, 73, 76, 81] ==> 683
[69, 73, 76, 83] ==> 684
[69, 73, 76, 86] ==> 685
[69, 73, 78] ==> 686
[69, 73, 81] ==> 687
[69, 73, 87] ==> 688
[69, 73, 88] ==> 689
[69, 73, 89] ==> 690
[69, 73] ==> 691
[69, 74, 90] ==> 692
[69, 74] ==> 693
[69, 78] ==> 694
[69, 80] ==> 695
[69, 83] ==> 696
[69, 84] ==> 697
[69, 85] ==> 698
[69, 86] ==> 699
[69, 87] ==> 700
[69, 88] ==> 701
[69] ==> 702
[70, 73] ==> 703
[70, 79] ==> 704
[70, 80] ==> 705
[70] ==> 706
[71, 74, 78] ==> 707
[71, 74, 80] ==> 708
[71, 74] ==> 709
[71, 75, 81] ==> 710
[71, 75] ==> 711
[71, 76, 81] ==> 712
[71, 78, 81] ==> 713
[71, 78] ==> 714
[71, 79] ==> 715
[71, 80] ==> 716
[71, 81] ==> 717
[71, 83] ==> 718
[71, 85] ==> 719
[71, 86] ==> 720
[71] ==> 721
[72, 74] ==> 722
[72, 75] ==> 723
[72, 79] ==> 724
[72, 81] ==> 725
[72] ==> 726
[73, 76, 81] ==> 727
[73, 76, 85] ==> 728
[73, 76] =

2 47 434 47 434 47 434 47 434 47 434 36 434 47 434 39 434 47 434 41 434 47 434 43 434 47 434 39 434 47 434 385 633 398 633 390 633 398 633 393 633 398 633 385 633 398 633 390 633 398 633 393 633 398 633 396 633 398 633 397 633 398 633 242 775 779 22 167 502 167 502 163 502 167 502 151 564 160 564 154 564 160 564 156 564 160 564 151 564 160 564 446 679 502 547 679 449 679 454 679 451 679 454 679 446 679 454 679 449 679 454 679 451 679 454 679 452 679 564 473 679 453 679 454 679 421 772 775 57 426 426 495 426 366 426 322 322 366 322 244 322 244 244 322 244 141 244 141 772 576 626 753 766 545 562 743 107 108 105 106 165 775 166 775 188 189 292 763 292 763 291 293 176 702 180 702 177 184 212 679 198 679 244 167 385 58 426 366 426 495 537 99 537 495 537 561 625 656 574 625 656 574 625 656 574 625 656 574 625 656 574 625 656 574 625 244 753 743 734 721 385 633 256 633 385 633 267 753 621 734 349 633 261 633 349 633 266 743 620 721 385 633 274 633 390 633 266 633 357 502 274 502 373 502 266 7

 723 722 722 704 772 766 763 766 772 773 662 721 743 766 773 781 784 782 776 770 705 740 772 704 638 770 757 734 660 661 639 572 724 572 557 724 557 505 726 746 766 772 776 782 786 789 786 783 779 773 766 753 734 559 434 502 545 564 633 657 662 702 564 633 657 662 702 721 734 743 702 721 734 743 753 763 766 772 734 743 753 763 766 772 775 779 781 785 788 785 781 785 772 781 763 772 781 772 763 772 743 763 702 743 763 743 702 743 657 702 564 743 726 721 702 487 487 487 753 743 726 721 556 556 556 743 726 721 702 662 502 721 341 743 502 564 781 776 775 772 715 564 715 564 715 564 783 781 776 775 772 564 725 564 725 564 781 776 775 772 715 715 783 781 776 775 739 739 781 776 775 772 740 740 782 781 776 773 770 770 781 776 773 770 766 757 746 743 726 706 702 662 726 706 702 662 641 576 702 662 641 576 564 509 482 564 721 662 743 721 775 766 781 776 775 772 766 757 753 743 726 662 753 726 766 753 776 766 776 766 753 726 766 753 726 662 721 679 743 721 766 743 775 766 781 776 775 772 766 757

In [40]:
idx_to_chords[1]

'[33, 45, 61, 64, 69, 81]'

In [1]:
data=['a','b','a','c','l','k','l']

In [2]:
data[0:2]

['a', 'b']

In [33]:
type(sorted(set(data)))

list

In [32]:
type(set(data))

set

In [42]:
dict(('a',1),('b',2) )

TypeError: dict expected at most 1 arguments, got 2

In [45]:
A= ['a','s','d']
for i,v in enumerate(A):
    print(v)

a
s
d


In [37]:
from midi_phraser import *

data = decode_midi('C:/Users/user/Desktop/研究所/程式/ML/midi_files/ff7prelu.mid')

all_chords = sorted(set(data))
n_chords = len(all_chords)
chords_to_idx = dict((v, i) for i,v in enumerate(all_chords))
idx_to_chords = dict((i, v) for i,v in enumerate(all_chords))

print('Total # of chords:',n_chords)
print('Total # of notes:',len(data))

length = 128
x_train, y_train = [], []

for idx in range(len(data)-length):
    sequence = data[idx:idx+length]
    next = data[idx+length]
        
    x_train.append([chords_to_idx[s] for s in sequence])
    y = np.zeros(n_chords)
    y[chords_to_idx[next]] = 1.
    y_train.append(y)

x_train, y_train = np.array(x_train), np.array(y_train)

from tensorflow.keras.layers import LSTM, Dropout, Dense
from tensorflow.keras.layers import Activation, Input, Embedding
from tensorflow.keras.models import Sequential, Model

model = Sequential()
model.add(Embedding(n_chords, 128, input_length=length))
model.add(LSTM(128, return_sequences=True))
model.add(Dropout(0.3))
model.add(LSTM(128, return_sequences=True))
model.add(Dropout(0.3))
model.add(LSTM(128))
model.add(Dropout(0.3))
model.add(Dense(n_chords))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

model.fit(x_train, y_train, epochs=200, batch_size=64)
model.save_weights('weights-ex03.h5')

Total # of chords: 104
Total # of notes: 831
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/200


KeyboardInterrupt: 

In [4]:
from midi_phraser import *

data = decode_midi('C:/Users/user/Desktop/研究所/程式/ML/midi_files/ff7prelu.mid')

all_chords = sorted(set(data))
n_chords = len(all_chords)
chords_to_idx = dict((v, i) for i,v in enumerate(all_chords))
idx_to_chords = dict((i, v) for i,v in enumerate(all_chords))

length = 128

from tensorflow.keras.layers import LSTM, Dropout, Dense
from tensorflow.keras.layers import Activation, Input, Embedding
from tensorflow.keras.models import Sequential, Model

model = Sequential()
model.add(Embedding(n_chords, 128, input_length=length))
model.add(LSTM(128, return_sequences=True))
model.add(Dropout(0.3))
model.add(LSTM(128, return_sequences=True))
model.add(Dropout(0.3))
model.add(LSTM(128))
model.add(Dropout(0.3))
model.add(Dense(n_chords))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

model.load_weights('weights-ex03.h5')#network架構出來，然後load

x_test = np.array([np.random.randint(0,n_chords,length)])
result = []
for seq in range(512):
    y_test = model.predict(x_test, verbose=0)[0]
    idx = np.argmax(y_test)
    result.append(idx_to_chords[idx])
    print('#%d: %s' % (seq,result[-1]))

    x_test[:,:-1] = x_test[:,1:]
    x_test[:,-1] = idx

encode_midi('test.mid', result)

C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


OSError: Unable to open file (unable to open file: name = 'weights-ex03.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [35]:
np.array([np.random.randint(0,5,10)])

array([[4, 4, 2, 1, 1, 1, 4, 0, 3, 4]])

In [38]:
x_train

array([[24, 25, 27, ..., 27, 24, 17],
       [25, 27, 31, ..., 24, 17, 13],
       [27, 31, 66, ..., 17, 13, 24],
       ...,
       [58, 44, 31, ..., 83, 84, 87],
       [44, 31, 25, ..., 84, 87, 88],
       [31, 25,  6, ..., 87, 88, 93]])

In [44]:
x_test=np.array([[1,2,3,4,5,6,7,8,9,]])

In [47]:
x_test[:,:-1]

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [42]:
x_test[:,:-1] = x_test[:,1:]

In [43]:
x_test

array([[2, 3, 4, 5, 6, 7, 8, 9, 9]])

In [352]:
from midi_phraser import *

sources = ['mozk216a.mid','mozk216b.mid','mozk216c.mid',
           'mozk218a.mid','mozk218b.mid','mozk218c.mid',
           'mozk219a.mid','mozk219b.mid','mozk219c.mid']
all_data = []
for src in sources:
    data = decode_midi(src, 2)
    all_data.append(data)

all_chords = sorted(set([s for data in all_data for s in data]))
n_chords = len(all_chords)
chords_to_idx = dict((v, i) for i,v in enumerate(all_chords))
idx_to_chords = dict((i, v) for i,v in enumerate(all_chords))

print('Total # of chords:',n_chords)

length = 128
x_train, y_train = [], []

for data_idx, data in enumerate(all_data):
    print('Song',data_idx,'- # of notes:',len(data))
    for idx in range(len(data)-length):
        sequence = data[idx:idx+length]
        next = data[idx+length]
        
        x_train.append([chords_to_idx[s] for s in sequence])
        y = np.zeros(n_chords)
        y[chords_to_idx[next]] = 1.
        y_train.append(y)

x_train, y_train = np.array(x_train), np.array(y_train)
print('Total # of training samples:',len(x_train))

# from tensorflow.keras.layers import LSTM, Dropout, Dense
# from tensorflow.keras.layers import Activation, Input, Embedding
# from tensorflow.keras.models import Sequential, Model

# model = Sequential()
# model.add(Embedding(n_chords, 128, input_length=length))
# model.add(LSTM(256, return_sequences=True))
# model.add(Dropout(0.3))
# model.add(LSTM(256, return_sequences=True))
# model.add(Dropout(0.3))
# model.add(LSTM(256))
# model.add(Dropout(0.3))
# model.add(Dense(n_chords))
# model.add(Activation('softmax'))
# model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

# model.fit(x_train, y_train, epochs=150, batch_size=64)
# model.save_weights('weights-ex04.h5')

Total # of chords: 745
Song 0 - # of notes: 3627
Song 1 - # of notes: 1516
Song 2 - # of notes: 2155
Song 3 - # of notes: 3419
Song 4 - # of notes: 1219
Song 5 - # of notes: 2220
Song 6 - # of notes: 3556
Song 7 - # of notes: 2065
Song 8 - # of notes: 2810
Total # of training samples: 21435


In [382]:
x_train

array([[624, 335, 624, ..., 575, 578, 575],
       [335, 624, 335, ..., 578, 575, 578],
       [624, 335, 248, ..., 575, 578, 710],
       ...,
       [310, 604, 310, ..., 618, 427, 532],
       [604, 310, 665, ..., 427, 532, 665],
       [310, 665,  83, ..., 532, 665, 427]])

In [49]:
cd C:/Users/user/Desktop/研究所/程式/ML/midi_files

C:\Users\user\Desktop\研究所\程式\ML\midi_files


In [51]:
from midi_phraser import *

sources = ['mozk216a.mid','mozk216b.mid','mozk216c.mid',
           'mozk218a.mid','mozk218b.mid','mozk218c.mid',
           'mozk219a.mid','mozk219b.mid','mozk219c.mid']
all_data = []
for src in sources:
    data = decode_midi(src, 2)
    all_data.append(data)

all_chords = sorted(set([s for data in all_data for s in data]))
n_chords = len(all_chords)
chords_to_idx = dict((v, i) for i,v in enumerate(all_chords))
idx_to_chords = dict((i, v) for i,v in enumerate(all_chords))

length = 128

from tensorflow.keras.layers import LSTM, Dropout, Dense
from tensorflow.keras.layers import Activation, Input, Embedding
from tensorflow.keras.models import Sequential, Model

model = Sequential()
model.add(Embedding(n_chords, 128, input_length=length))
model.add(LSTM(256, return_sequences=True))
model.add(Dropout(0.3))
model.add(LSTM(256, return_sequences=True))
model.add(Dropout(0.3))
model.add(LSTM(256))
model.add(Dropout(0.3))
model.add(Dense(n_chords))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

model.load_weights('C:/Users/user/Desktop/研究所/程式/ML/weights-ex04.h5')

x_test = np.array([np.random.randint(0,n_chords,length)])
result = []
temperature=0.5
for seq in range(512):
    y_test = model.predict(x_test, verbose=0)[0]
    
    repeats = [np.all(x_test[:,-n:]==x_test[:,-n*2:-n]) for n in [2,3,4]]
    if np.any(repeats): temperature *= 1.20
    else: temperature *= 0.95
    temperature = min(max(temperature, 0.2),5.0)
    
    y_test = y_test**(1./temperature)
    idx = np.random.choice(range(n_chords),p=y_test/y_test.sum())
    result.append(idx_to_chords[idx])
    print('#%d: %s, T=%.2f' % (seq,result[-1],temperature))
    
    x_test[:,:-1] = x_test[:,1:]
    x_test[:,-1] = idx

encode_midi('test.mid', result)

#0: [73, 78], T=0.47
#1: [67, 71], T=0.45
#2: [64, 76], T=0.43
#3: [62, 74], T=0.41
#4: [67, 71], T=0.39
#5: [62, 83], T=0.37
#6: [73, 81], T=0.35
#7: [61, 81], T=0.33
#8: [62, 74], T=0.32
#9: [74, 83], T=0.30
#10: [73, 81], T=0.28
#11: [74], T=0.27
#12: [68, 71], T=0.26
#13: [57], T=0.24
#14: [69, 74], T=0.23
#15: [66, 69], T=0.22
#16: [69, 74], T=0.21
#17: [77], T=0.20
#18: [66, 69], T=0.20
#19: [73], T=0.20
#20: [62, 66], T=0.20
#21: [66, 69], T=0.20
#22: [66, 69], T=0.20
#23: [88], T=0.20
#24: [66, 69], T=0.20
#25: [66, 69], T=0.20
#26: [66, 69], T=0.20
#27: [66, 69], T=0.20
#28: [66, 69], T=0.24
#29: [66, 69], T=0.29
#30: [66, 69], T=0.35
#31: [66, 69], T=0.41
#32: [66, 69], T=0.50
#33: [69, 78], T=0.60
#34: [66, 69], T=0.57
#35: [69, 78], T=0.54
#36: [66, 69], T=0.65
#37: [67, 71], T=0.78
#38: [69, 72], T=0.74
#39: [69, 78], T=0.70
#40: [71, 74], T=0.67
#41: [68, 76], T=0.63
#42: [67, 71], T=0.60
#43: [73, 76], T=0.57
#44: [63, 66], T=0.54
#45: [72, 81], T=0.51
#46: [83], T=0.49


#394: [71, 76], T=0.30
#395: [78], T=0.28
#396: [76], T=0.27
#397: [78], T=0.26
#398: [73, 76], T=0.24
#399: [78], T=0.23
#400: [76], T=0.22
#401: [78], T=0.21
#402: [73, 76], T=0.20
#403: [78], T=0.24
#404: [76], T=0.29
#405: [78], T=0.35
#406: [73, 76], T=0.41
#407: [78], T=0.50
#408: [76], T=0.60
#409: [78], T=0.72
#410: [76], T=0.86
#411: [78], T=1.03
#412: [74, 78], T=1.24
#413: [78], T=1.18
#414: [64, 80], T=1.12
#415: [78], T=1.06
#416: [76], T=1.01
#417: [78], T=0.96
#418: [76], T=0.91
#419: [78], T=1.09
#420: [73, 76], T=1.31
#421: [78], T=1.25
#422: [76], T=1.18
#423: [78], T=1.12
#424: [64, 76], T=1.07
#425: [78], T=1.01
#426: [76], T=0.96
#427: [78], T=0.92
#428: [76], T=0.87
#429: [78], T=1.04
#430: [76], T=1.25
#431: [78], T=1.50
#432: [64, 74], T=1.80
#433: [74, 83], T=1.71
#434: [55, 62], T=1.63
#435: [73, 76], T=1.55
#436: [64, 67], T=1.47
#437: [65, 69], T=1.40
#438: [64, 81], T=1.33
#439: [74, 78], T=1.26
#440: [69, 74], T=1.20
#441: [57, 74], T=1.14
#442: [69, 81], 

In [83]:
x_test=np.array([[1,2,3,4,5,8,9,8,9,]])

In [66]:
[np.all(x_test[:,-n:]==x_test[:,-n*2:-n]) for n in [2,3,4]]

[True, False, False]

In [61]:
x_test[:,-3:]

array([[7, 8, 9]])

In [62]:
x_test[:,-3*2:-3]

array([[4, 5, 6]])

In [67]:
np.any([np.all(x_test[:,-n:]==x_test[:,-n*2:-n]) for n in [2,3,4]])

True

In [87]:
x_test**(0.5)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.82842712, 3.        , 2.82842712, 3.        ]])

In [ ]:
np.random.choice(range(n_chords),p=y_test/y_test.sum())

In [89]:
range(5)

range(0, 5)

In [113]:
np.random.choice(np.array([0,1,2,3,4]),p=[0.2,0.2,0.2,0.2,0.2])

2

In [108]:
type(range(5))

range

In [231]:
input='lntsfu'

In [210]:
import numpy as np

def string_to_onehot(input):
    output = np.zeros(27)
    if len(input)>=2: output = np.zeros((len(input),27))
    ### START YOUR CODE HERE ###
    if  (len(input)==1):
        if (input!=' '):
                output[ord(input)-96]=1.
        else :
                output[0]=1.
    else :
        for i in range(len(input)):
            if (input[i]!=' '):
                output[i][ord(input[i])-96]=1.
            else :
                output[i][0]=1.

    #### END YOUR CODE HERE ####
    return output


In [211]:
input[1]

'n'

In [212]:
string_to_onehot(input)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [126]:
ord('a')

97

In [177]:
output = np.zeros(27)

In [180]:
np.all(output == np.zeros(27))

True

In [179]:
output

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [204]:
# output = np.zeros(27)
output = np.zeros((len(input),27))

In [250]:
len(source_string)

110

In [232]:
str='fccccc'

In [233]:
str[1]

'c'

In [8]:
source_string='following the previous exercise now we are going to build with a network model based on long short term memozy'

In [104]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense,Reshape
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Activation, Embedding
def string_to_onehot(input):

    output = np.zeros((len(input),27))
    for i in range(len(input)):
        if (input[i]!=' '):
            output[i][ord(input[i])-96]=1.
        else :
            output[i][0]=1.

    #### END YOUR CODE HERE ####
    return output


def build_network_model(source_string):
    ### START YOUR CODE HERE ###
    
    source_string_decode=string_to_onehot(source_string)
    x_train = np.zeros((100,10,27))
    x_train_number=np.zeros((100,10))
    y_train = np.zeros((100,27))
    
    for i in range(100):
        x_train[i]=source_string_decode[0+i:10+i]
        y_train[i]=source_string_decode[10+i]
        x_train_number[i]=[np.argmax(x_train[i][n]) for n in range(len(x_train[i]))]
        
#     x_train=x_train_number

    model = Sequential()
#     model.add(Embedding(input_dim=27, output_dim=10, input_length=10))#輸入是10，輸出是10*10(每一格的上限是26)

#     model.add(Reshape((270,), input_shape=(10,27)))#not apply for LSTM

#     model.add(Reshape((270,), input_shape=(10,27)))
#     model.add(Embedding(input_dim=27, output_dim=1, input_length=270))
    
    

    model.add(LSTM(100, input_shape=(10, 27)))  
#     model.add(LSTM(100))
    model.add(Dense(27))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer=Adam())

    model.fit(x_train, y_train, epochs=100, batch_size=20)
    
    #### END YOUR CODE HERE ####
    return model

In [105]:
build_network_model(source_string)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
100/100 [==============================] - 2s 21ms/sample - loss: 3.2921
Epoch 2/100
100/100 [==============================] - 0s 3ms/sample - loss: 3.2583
Epoch 3/100
100/100 [==============================] - 0s 1ms/sample - loss: 3.2162
Epoch 4/100
100/100 [==============================] - 0s 1ms/sample - loss: 3.1536
Epoch 5/100
100/100 [==============================] - 0s 1ms/sample - loss: 3.0341
Epoch 6/100
100/100 [==============================] - 0s 1ms/sample - loss: 2.9221
Epoch 7/100
100/100 [==============================] - 0s 1ms/sample - loss: 2.8847
Epoch 8/100
100/100 [==============================] - 0s 1ms/sample - loss: 2.8113
Epoch 9/100
100/100 [==============================] - 0s 1ms/sample - loss: 2.8154
Epoch 10/100
100/100 [==============================] - 0s 1ms/sample - loss: 2.8010
Epoch 11/100
100/100 [==============================] - 0s 990us

100/100 [==============================] - 0s 1ms/sample - loss: 0.1688
Epoch 94/100
100/100 [==============================] - 0s 920us/sample - loss: 0.1612
Epoch 95/100
100/100 [==============================] - 0s 900us/sample - loss: 0.1550
Epoch 96/100
100/100 [==============================] - 0s 880us/sample - loss: 0.1493
Epoch 97/100
100/100 [==============================] - 0s 910us/sample - loss: 0.1447
Epoch 98/100
100/100 [==============================] - 0s 950us/sample - loss: 0.1404
Epoch 99/100
100/100 [==============================] - 0s 1ms/sample - loss: 0.1347
Epoch 100/100
100/100 [==============================] - 0s 950us/sample - loss: 0.1309


In [75]:
input_shape = (x_train.shape[1], 1)

NameError: name 'x_train' is not defined

In [ ]:
def string_to_onehot(input):

    output = np.zeros((len(input),27))
    for i in range(len(input)):
        if (input[i]!=' '):
            output[i][ord(input[i])-96]=1.
        else :
            output[i][0]=1.

    #### END YOUR CODE HERE ####
    return output

In [254]:
string_to_onehot('abc')

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [256]:
np.argmax(np.array([1,2,3]))

2

In [ ]:
#HW1

In [ ]:
import numpy as np

def string_to_onehot(input):
    output = np.zeros(27)
    if len(input)>=2: output = np.zeros((len(input),27))
    ### START YOUR CODE HERE ###
    if  (len(input)==1):
        if (input!=' '):
                output[ord(input)-96]=1.
        else :
                output[0]=1.
    else :
        for i in range(len(input)):
            if (input[i]!=' '):
                output[i][ord(input[i])-96]=1.
            else :
                output[i][0]=1.

    #### END YOUR CODE HERE ####
    return output


In [ ]:
#HW2

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense,Reshape
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Activation, Embedding
def string_to_onehot(input):

    output = np.zeros((len(input),27))
    for i in range(len(input)):
        if (input[i]!=' '):
            output[i][ord(input[i])-96]=1.
        else :
            output[i][0]=1.

    return output


def build_network_model(source_string):
    ### START YOUR CODE HERE ###
    
    source_string_decode=string_to_onehot(source_string)
    x_train = np.zeros((100,10,27))
    x_train_number=np.zeros((100,10))
    y_train = np.zeros((100,27))
    
    for i in range(100):
        x_train[i]=source_string_decode[0+i:10+i]
        y_train[i]=source_string_decode[10+i]

    model = Sequential()
    model.add(LSTM(100, input_shape=(10, 27)))  
    model.add(Dense(27))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer=Adam())

    model.fit(x_train, y_train, epochs=100, batch_size=20)
    
    #### END YOUR CODE HERE ####
    return model